/* AUTOMATICALLY GENERATED by qapi-gen.py DO NOT MODIFY */

/*
 * Schema-defined QAPI types
 *
 * Copyright IBM, Corp. 2011
 * Copyright (c) 2013-2018 Red Hat Inc.
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 */

#include "qemu/osdep.h"
#include "qapi/dealloc-visitor.h"
#include "vee-qapi-types.h"
#include "vee-qapi-visit.h"

void qapi_free_QmpVeeSSD1306Pixel(QmpVeeSSD1306Pixel *obj)
{
    Visitor *v;

    if (!obj) {
        return;
    }

    v = qapi_dealloc_visitor_new();
    visit_type_QmpVeeSSD1306Pixel(v, NULL, &obj, NULL);
    visit_free(v);
}

void qapi_free_QmpVeeVmTimeUs(QmpVeeVmTimeUs *obj)
{
    Visitor *v;

    if (!obj) {
        return;
    }

    v = qapi_dealloc_visitor_new();
    visit_type_QmpVeeVmTimeUs(v, NULL, &obj, NULL);
    visit_free(v);
}

/* Dummy declaration to prevent empty .o file */
char qapi_dummy_vee_qapi_types_c;
