/* AUTOMATICALLY GENERATED by qapi-gen.py DO NOT MODIFY */

/*
 * QAPI Commands initialization
 *
 * Copyright IBM, Corp. 2011
 * Copyright (C) 2014-2018 Red Hat, Inc.
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 */

#include "qemu/osdep.h"
#include "vee-qapi-commands.h"
#include "vee-qapi-init-commands.h"

void vee_qmp_init_marshal(QmpCommandList *cmds)
{
    QTAILQ_INIT(cmds);

    qmp_register_command(cmds, "vee-command",
                         qmp_marshal_vee_command, 0, 0);
    qmp_register_command(cmds, "vee-ssd1306-get-pixel",
                         qmp_marshal_vee_ssd1306_get_pixel, 0, 0);
    qmp_register_command(cmds, "vee-vm-feed",
                         qmp_marshal_vee_vm_feed, 0, 0);
    qmp_register_command(cmds, "vee-get-vm-time-us",
                         qmp_marshal_vee_get_vm_time_us, 0, 0);
}

/* Dummy declaration to prevent empty .o file */
char qapi_dummy_vee_qapi_init_commands_c;
