/* AUTOMATICALLY GENERATED by qapi-gen.py DO NOT MODIFY */

/*
 * QAPI Events emission
 *
 * Copyright (c) 2014 Wenchao Xia
 * Copyright (c) 2015-2018 Red Hat Inc.
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 */

#ifndef VEE_QAPI_EMIT_EVENTS_H
#define VEE_QAPI_EMIT_EVENTS_H

#include "qapi/util.h"

typedef enum vee_QAPIEvent {
    VEE_QAPI_EVENT_VEE_EVENT,
    VEE_QAPI_EVENT_VEE_VM_FEED_TICK_EVENT,
    VEE_QAPI_EVENT__MAX,
} vee_QAPIEvent;

#define vee_QAPIEvent_str(val) \
    qapi_enum_lookup(&vee_QAPIEvent_lookup, (val))

extern const QEnumLookup vee_QAPIEvent_lookup;

void vee_qapi_event_emit(vee_QAPIEvent event, QDict *qdict);

#endif /* VEE_QAPI_EMIT_EVENTS_H */
