/* AUTOMATICALLY GENERATED by qapi-gen.py DO NOT MODIFY */

/*
 * Schema-defined QAPI types
 *
 * Copyright IBM, Corp. 2011
 * Copyright (c) 2013-2018 Red Hat Inc.
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 */

#ifndef VEE_QAPI_TYPES_H
#define VEE_QAPI_TYPES_H

#include "qapi/qapi-builtin-types.h"

typedef struct QmpVeeSSD1306Pixel QmpVeeSSD1306Pixel;

typedef struct q_obj_vee_ssd1306_get_pixel_arg q_obj_vee_ssd1306_get_pixel_arg;

typedef struct q_obj_vee_vm_feed_arg q_obj_vee_vm_feed_arg;

typedef struct QmpVeeVmTimeUs QmpVeeVmTimeUs;

typedef struct q_obj_VEE_VM_FEED_TICK_EVENT_arg q_obj_VEE_VM_FEED_TICK_EVENT_arg;

struct QmpVeeSSD1306Pixel {
    int64_t width;
    int64_t height;
    intList *pixel;
};

void qapi_free_QmpVeeSSD1306Pixel(QmpVeeSSD1306Pixel *obj);
G_DEFINE_AUTOPTR_CLEANUP_FUNC(QmpVeeSSD1306Pixel, qapi_free_QmpVeeSSD1306Pixel)

struct q_obj_vee_ssd1306_get_pixel_arg {
    char *path;
};

struct q_obj_vee_vm_feed_arg {
    int64_t count;
};

struct QmpVeeVmTimeUs {
    int64_t time;
};

void qapi_free_QmpVeeVmTimeUs(QmpVeeVmTimeUs *obj);
G_DEFINE_AUTOPTR_CLEANUP_FUNC(QmpVeeVmTimeUs, qapi_free_QmpVeeVmTimeUs)

struct q_obj_VEE_VM_FEED_TICK_EVENT_arg {
    int64_t time;
};

#endif /* VEE_QAPI_TYPES_H */
