/* AUTOMATICALLY GENERATED by qapi-gen.py DO NOT MODIFY */

/*
 * QAPI Events emission
 *
 * Copyright (c) 2014 Wenchao Xia
 * Copyright (c) 2015-2018 Red Hat Inc.
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 */

#include "qemu/osdep.h"
#include "vee-qapi-emit-events.h"

const QEnumLookup vee_QAPIEvent_lookup = {
    .array = (const char *const[]) {
        [VEE_QAPI_EVENT_VEE_EVENT] = "VEE_EVENT",
        [VEE_QAPI_EVENT_VEE_VM_FEED_TICK_EVENT] = "VEE_VM_FEED_TICK_EVENT",
    },
    .size = VEE_QAPI_EVENT__MAX
};

/* Dummy declaration to prevent empty .o file */
char qapi_dummy_vee_qapi_emit_events_c;
