/* AUTOMATICALLY GENERATED by qapi-gen.py DO NOT MODIFY */

/*
 * Schema-defined QAPI/QMP events
 *
 * Copyright (c) 2014 Wenchao Xia
 * Copyright (c) 2015-2018 Red Hat Inc.
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 */

#include "qemu/osdep.h"
#include "vee-qapi-emit-events.h"
#include "vee-qapi-events.h"
#include "vee-qapi-visit.h"
#include "qapi/compat-policy.h"
#include "qapi/error.h"
#include "qapi/qmp/qdict.h"
#include "qapi/qmp-event.h"

void qapi_event_send_vee_event(void)
{
    QDict *qmp;

    qmp = qmp_event_build_dict("VEE_EVENT");

    vee_qapi_event_emit(VEE_QAPI_EVENT_VEE_EVENT, qmp);

    qobject_unref(qmp);
}

void qapi_event_send_vee_vm_feed_tick_event(int64_t time)
{
    QDict *qmp;
    QObject *obj;
    Visitor *v;
    q_obj_VEE_VM_FEED_TICK_EVENT_arg param = {
        time
    };

    qmp = qmp_event_build_dict("VEE_VM_FEED_TICK_EVENT");

    v = qobject_output_visitor_new_qmp(&obj);

    visit_start_struct(v, "VEE_VM_FEED_TICK_EVENT", NULL, 0, &error_abort);
    visit_type_q_obj_VEE_VM_FEED_TICK_EVENT_arg_members(v, &param, &error_abort);
    visit_check_struct(v, &error_abort);
    visit_end_struct(v, NULL);

    visit_complete(v, &obj);
    if (qdict_size(qobject_to(QDict, obj))) {
        qdict_put_obj(qmp, "data", obj);
    } else {
        qobject_unref(obj);
    }
    vee_qapi_event_emit(VEE_QAPI_EVENT_VEE_VM_FEED_TICK_EVENT, qmp);

    visit_free(v);
    qobject_unref(qmp);
}

/* Dummy declaration to prevent empty .o file */
char qapi_dummy_vee_qapi_events_c;
