/* AUTOMATICALLY GENERATED by qapi-gen.py DO NOT MODIFY */

/*
 * Schema-defined QAPI/QMP commands
 *
 * Copyright IBM, Corp. 2011
 * Copyright (C) 2014-2018 Red Hat, Inc.
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 */

#ifndef VEE_QAPI_COMMANDS_H
#define VEE_QAPI_COMMANDS_H

#include "vee-qapi-types.h"

void qmp_vee_command(Error **errp);
void qmp_marshal_vee_command(QDict *args, QObject **ret, Error **errp);
QmpVeeSSD1306Pixel *qmp_vee_ssd1306_get_pixel(const char *path, Error **errp);
void qmp_marshal_vee_ssd1306_get_pixel(QDict *args, QObject **ret, Error **errp);
void qmp_vee_vm_feed(int64_t count, Error **errp);
void qmp_marshal_vee_vm_feed(QDict *args, QObject **ret, Error **errp);
QmpVeeVmTimeUs *qmp_vee_get_vm_time_us(Error **errp);
void qmp_marshal_vee_get_vm_time_us(QDict *args, QObject **ret, Error **errp);

#endif /* VEE_QAPI_COMMANDS_H */
