/* AUTOMATICALLY GENERATED by qapi-gen.py DO NOT MODIFY */

/*
 * Schema-defined QAPI/QMP events
 *
 * Copyright (c) 2014 Wenchao Xia
 * Copyright (c) 2015-2018 Red Hat Inc.
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 */

#ifndef VEE_QAPI_EVENTS_H
#define VEE_QAPI_EVENTS_H

#include "qapi/util.h"
#include "vee-qapi-types.h"

void qapi_event_send_vee_event(void);

void qapi_event_send_vee_vm_feed_tick_event(int64_t time);

#endif /* VEE_QAPI_EVENTS_H */
