/* AUTOMATICALLY GENERATED by qapi-gen.py DO NOT MODIFY */

/*
 * Schema-defined QAPI visitors
 *
 * Copyright IBM, Corp. 2011
 * Copyright (C) 2014-2018 Red Hat, Inc.
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 */

#include "qemu/osdep.h"
#include "qapi/error.h"
#include "vee-qapi-visit.h"

bool visit_type_QmpVeeSSD1306Pixel_members(Visitor *v, QmpVeeSSD1306Pixel *obj, Error **errp)
{
    if (!visit_type_int(v, "width", &obj->width, errp)) {
        return false;
    }
    if (!visit_type_int(v, "height", &obj->height, errp)) {
        return false;
    }
    if (!visit_type_intList(v, "pixel", &obj->pixel, errp)) {
        return false;
    }
    return true;
}

bool visit_type_QmpVeeSSD1306Pixel(Visitor *v, const char *name,
                 QmpVeeSSD1306Pixel **obj, Error **errp)
{
    bool ok = false;

    if (!visit_start_struct(v, name, (void **)obj, sizeof(QmpVeeSSD1306Pixel), errp)) {
        return false;
    }
    if (!*obj) {
        /* incomplete */
        assert(visit_is_dealloc(v));
        ok = true;
        goto out_obj;
    }
    if (!visit_type_QmpVeeSSD1306Pixel_members(v, *obj, errp)) {
        goto out_obj;
    }
    ok = visit_check_struct(v, errp);
out_obj:
    visit_end_struct(v, (void **)obj);
    if (!ok && visit_is_input(v)) {
        qapi_free_QmpVeeSSD1306Pixel(*obj);
        *obj = NULL;
    }
    return ok;
}

bool visit_type_q_obj_vee_ssd1306_get_pixel_arg_members(Visitor *v, q_obj_vee_ssd1306_get_pixel_arg *obj, Error **errp)
{
    if (!visit_type_str(v, "path", &obj->path, errp)) {
        return false;
    }
    return true;
}

bool visit_type_q_obj_vee_vm_feed_arg_members(Visitor *v, q_obj_vee_vm_feed_arg *obj, Error **errp)
{
    if (!visit_type_int(v, "count", &obj->count, errp)) {
        return false;
    }
    return true;
}

bool visit_type_QmpVeeVmTimeUs_members(Visitor *v, QmpVeeVmTimeUs *obj, Error **errp)
{
    if (!visit_type_int(v, "time", &obj->time, errp)) {
        return false;
    }
    return true;
}

bool visit_type_QmpVeeVmTimeUs(Visitor *v, const char *name,
                 QmpVeeVmTimeUs **obj, Error **errp)
{
    bool ok = false;

    if (!visit_start_struct(v, name, (void **)obj, sizeof(QmpVeeVmTimeUs), errp)) {
        return false;
    }
    if (!*obj) {
        /* incomplete */
        assert(visit_is_dealloc(v));
        ok = true;
        goto out_obj;
    }
    if (!visit_type_QmpVeeVmTimeUs_members(v, *obj, errp)) {
        goto out_obj;
    }
    ok = visit_check_struct(v, errp);
out_obj:
    visit_end_struct(v, (void **)obj);
    if (!ok && visit_is_input(v)) {
        qapi_free_QmpVeeVmTimeUs(*obj);
        *obj = NULL;
    }
    return ok;
}

bool visit_type_q_obj_VEE_VM_FEED_TICK_EVENT_arg_members(Visitor *v, q_obj_VEE_VM_FEED_TICK_EVENT_arg *obj, Error **errp)
{
    if (!visit_type_int(v, "time", &obj->time, errp)) {
        return false;
    }
    return true;
}

/* Dummy declaration to prevent empty .o file */
char qapi_dummy_vee_qapi_visit_c;
