/* AUTOMATICALLY GENERATED by qapi-gen.py DO NOT MODIFY */

/*
 * Schema-defined QAPI visitors
 *
 * Copyright IBM, Corp. 2011
 * Copyright (C) 2014-2018 Red Hat, Inc.
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 */

#ifndef VEE_QAPI_VISIT_H
#define VEE_QAPI_VISIT_H

#include "qapi/qapi-builtin-visit.h"
#include "vee-qapi-types.h"


bool visit_type_QmpVeeSSD1306Pixel_members(Visitor *v, QmpVeeSSD1306Pixel *obj, Error **errp);

bool visit_type_QmpVeeSSD1306Pixel(Visitor *v, const char *name,
                 QmpVeeSSD1306Pixel **obj, Error **errp);

bool visit_type_q_obj_vee_ssd1306_get_pixel_arg_members(Visitor *v, q_obj_vee_ssd1306_get_pixel_arg *obj, Error **errp);

bool visit_type_q_obj_vee_vm_feed_arg_members(Visitor *v, q_obj_vee_vm_feed_arg *obj, Error **errp);

bool visit_type_QmpVeeVmTimeUs_members(Visitor *v, QmpVeeVmTimeUs *obj, Error **errp);

bool visit_type_QmpVeeVmTimeUs(Visitor *v, const char *name,
                 QmpVeeVmTimeUs **obj, Error **errp);

bool visit_type_q_obj_VEE_VM_FEED_TICK_EVENT_arg_members(Visitor *v, q_obj_VEE_VM_FEED_TICK_EVENT_arg *obj, Error **errp);

#endif /* VEE_QAPI_VISIT_H */
